export default {
    home: require('../asset/home.png'),
  menu:require('../asset/list.png'),
  heartDo:require('../asset/heartDo.png'),
  heartDen:require('../asset/heartDen.png'),
  star : require('../asset/star.png'),
  user:require('../asset/user.png'),
  settings: require('../asset/settings.png'),
  lock :require('../asset/padlock.png'),
  logout: require('../asset/logout.png'),
  email:require('../asset/email.png'),
  phone:require('../asset/telephone.png'),
  cloud:require('../asset/cloud.png'),
  lockapp: require('../asset/lockapp.png'),
  next:require('../asset/next.png'),
  bluetooth:require('../asset/bluetooth.png'),
  notification:require('../asset/notification.png'),
  settings:require('../asset/settings.png'),
  food:require('../asset/dish.png'),
  electricity:require('../asset/electricity.png'),
  shoppimg:require('../asset/shopping.png'),
  back:require('../asset/back.png'),
  search:require('../asset/search.png'),
  table: require('../asset/table.png'),
  tableBig: require('../asset/tableBig.png'),
  close: require('../asset/close.png'),
};
