export  const IconImage = [{
    fire: require('../asset/fire.png'),
    home: require('../asset/home.png'),
    facebook: require('../asset/facebook1.png'),
    gmail: require('../asset/gmail.png'),
    instagram:require('../asset/instagram.png'),
 
    heartDo:require('../asset/heartDo.png'),
    heartDen:require('../asset/heartDen.png'),
    star : require('../asset/star.png'),
    world:require('../asset/world.png'),
    settings: require('../asset/settings.png'),
    lock :require('../asset/padlock.png'),
    logout: require('../asset/logout.png'),
    email:require('../asset/email.png'),
    phone:require('../asset/telephone.png'),
    cloud:require('../asset/cloud.png'),
    lockapp: require('../asset/lockapp.png'),
    next:require('../asset/next.png'),
    bluetooth:require('../asset/bluetooth.png'),
    fingerprint:require('../asset/fingerprint.png'),
    sound:require('../asset/sound.png'),
    notification:require('../asset/notification.png'),
    settings:require('../asset/settings.png'),
    food:require('../asset/dish.png'),
    electricity:require('../asset/electricity.png'),
}]