export const ListData = [
    {
      nameProduct: ' Máy hút bụi Samsung VC18M21M0VN/SV-N',
      url: 'https://cdn.tgdd.vn/Products/Images/1990/157525/samsung-vc18m21m0vn-sv-n-300x300.jpg',
      price: 75,
      specifications: [
        'Dry clear',
        'cyclone filer',
        'Convenience cost storage',
      ],
      review: 19,
      stars: 5,
    },
    {
      nameProduct: 'Máy hút bụi ROLER RC-2113',
      url: 'https://cdn.mediamart.vn/images/Upload/images/3(457).png',
      price: 56,
      specifications: [
        'Lim design',
        'Easy to maneuver',
        'Stands upright to storage',
      ],
      review: 9,
      stars: 4,
    },

    {
      nameProduct: 'Máy hút bụi Electrolux Z1220',
      url: 'https://hc.com.vn/i/ecommerce/media/00029375_FEATURE_51461.jpg',
      price: 120,
      specifications: [
        'Dry clear',
        'Stands upright to storage',
        'Convenience cost storage',
      ],
      review: 119,
      stars: 2,
    },
    {
      nameProduct: 'Máy Hút Bụi Electrolux ZB3314AK',
      url: 'https://cdn.nguyenkimmall.com/images/detailed/513/10036162-may-hut-bui-electrolux-zb3314ak-1.jpg',
      price: 140,
      specifications: [
        'Dry clear',
        'Easy to maneuver',
        'Convenience cost storage',
        'Excellent filtration',
      ],
      review: 133,
      stars: 1,
    },
    {
      nameProduct: 'Máy hút bụi công nghiệp Palada PD70',
      url: 'https://dienmaybamien.com/media/product/944_may_hut_bui_palada_pd_70.jpg',
      price: 112,
      specifications: [
        'Easy to maneuver',
        'Cyclone filer',
        'Convenience cost storage',
        'Heavy',
      ],
      review: 444,
      stars: 3,
    },
    {
      nameProduct: 'Robot hút bụi thông minh Klemax X550',
      url: 'http://timemart.vn/publish/thumbnail/305/305x310xfull/upload/305/20140708/robot-klemax-550.jpg',
      price: 340,
      specifications: [
        'Dry clear ',
        'Clean the air and mop the floor ',
        'Convenience cost storage',
        'High performance',
      ],
      review: 1333,
      stars: 5,
    },
    {
      nameProduct: 'Robot HOM-BOT LG VR5906LM',
      url: 'https://www.lg.com/vn/images/may-hut-bui/vr5906lm/gallery/large01.jpg',
      price: 280,
      specifications: [
        'High performance',
        'Easy to maneuver',
        'Convenience cost storage',
        'Excellent filtration',
      ],
      review: 3323,
      stars: 2,
    },
    {
      nameProduct: 'Robot HOM-BOT LG VR5906LM',
      url: 'https://www.lg.com/vn/images/may-hut-bui/vr5906lm/gallery/large01.jpg',
      price: 280,
      specifications: [
        'High performance',
        'Easy to maneuver',
        'Convenience cost storage',
        'Excellent filtration',
      ],
      review: 3323,
      stars: 2,
    },
  ]